### ISSUE TITLE
Can't build on Ubuntu - nlohmann/json.hpp: No such file or directory

### ISSUE THREAD

**Issue by atlex** [swiftraccoon/cpp-sdrtrunk-transcriber#29]
Operating System: Ubuntu 22.04.4 LTS              
Kernel: Linux 6.5.0-28-generic

$ make

[  2%] Built target CLI11
[  2%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
[  4%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
[  6%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[  8%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
[ 10%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/depthguard.cpp.o
[ 12%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
[ 14%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o
[ 17%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o
[ 19%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o
[ 21%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o
[ 23%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o
[ 25%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exceptions.cpp.o
[ 27%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o
[ 29%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o
[ 31%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node.cpp.o
[ 34%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o
[ 36%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o
[ 38%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o
[ 40%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/null.cpp.o
[ 42%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o
[ 44%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o
[ 46%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o
[ 48%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/regex_yaml.cpp.o
[ 51%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o
[ 53%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o
[ 55%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o
[ 57%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o
[ 59%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o
[ 61%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o
[ 63%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o
[ 65%] Building CXX object external/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
[ 68%] Linking CXX static library libyaml-cpp.a
[ 68%] Built target yaml-cpp
[ 70%] Building CXX object external/yaml-cpp/util/CMakeFiles/yaml-cpp-read.dir/read.cpp.o
[ 72%] Building CXX object external/yaml-cpp/util/CMakeFiles/yaml-cpp-parse.dir/parse.cpp.o
[ 74%] Building CXX object external/yaml-cpp/util/CMakeFiles/yaml-cpp-sandbox.dir/sandbox.cpp.o
[ 76%] Building CXX object CMakeFiles/sdrTrunkTranscriber.dir/src/main.cpp.o
[ 78%] Linking CXX executable parse
[ 80%] Linking CXX executable read
[ 82%] Linking CXX executable sandbox
[ 82%] Built target yaml-cpp-sandbox
[ 82%] Built target yaml-cpp-read
[ 87%] Building CXX object CMakeFiles/sdrTrunkTranscriber.dir/src/curlHelper.cpp.o
[ 87%] Building CXX object CMakeFiles/sdrTrunkTranscriber.dir/src/DatabaseManager.cpp.o
[ 87%] Built target yaml-cpp-parse
[ 89%] Building CXX object CMakeFiles/sdrTrunkTranscriber.dir/src/fileProcessor.cpp.o
[ 91%] Building CXX object CMakeFiles/sdrTrunkTranscriber.dir/src/ConfigSingleton.cpp.o
[ 93%] Building CXX object CMakeFiles/sdrTrunkTranscriber.dir/src/transcriptionProcessor.cpp.o
/home/pi/cpp-sdrtrunk-transcriber/src/transcriptionProcessor.cpp:15:10: fatal error: nlohmann/json.hpp: No such file or directory
   15 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sdrTrunkTranscriber.dir/build.make:146: CMakeFiles/sdrTrunkTranscriber.dir/src/transcriptionProcessor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:219: CMakeFiles/sdrTrunkTranscriber.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by atlex** [comment]
Any Ideas?

**Comment by helix26j** [comment]
On Ubuntu jammy, using apt search nlohmann I found the following package that seemed to meet the requirement:
`sudo apt install nlohmann-json3-dev`

**Comment by swiftraccoon** [comment]
Ahh! Apologies. I completely missed the e-mail from you opening the issue. :( 

The automated build testing for Ubuntu is available for review:
- https://github.com/swiftraccoon/cpp-sdrtrunk-transcriber/blob/main/.github/workflows/cmake-ubuntu.yml
- https://github.com/swiftraccoon/cpp-sdrtrunk-transcriber/tree/main/build-testing

Let me know if neither of these are helpful and the package that helix26j mentioned does not resolve your issue. 

I've just now released a much more efficient and simpler version of all of this that is in Python only, in case Python is easier and would be your preference:
- https://github.com/swiftraccoon/effective-guacamolea/blob/main/transcriber.py

**Comment by atlex** [comment]
@helix26j @swiftraccoon

Yes

`$ sudo apt install nlohmann-json3-dev`

It fixed this issue. Thank you!
